version: "3.9"

services:

  postgres:
    image: postgres:16-alpine
    container_name: zarvix-db
    restart: unless-stopped
    environment:
      POSTGRES_USER:     ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?La variable POSTGRES_PASSWORD es obligatoria}
      POSTGRES_DB:       ${POSTGRES_DB:-zarvix}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: zarvix-backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV:       production
      PORT:           3000
      DATABASE_URL:   postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-zarvix}?sslmode=disable
      JWT_SECRET:     ${JWT_SECRET:?La variable JWT_SECRET es obligatoria}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:?La variable ADMIN_PASSWORD es obligatoria}
    ports:
      - "3000:3000"

volumes:
  postgres_data:
